badoo/Reaktive

- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/scheduler/ExecutorServiceScheduler.kt
> Fixed ExecutorServiceScheduler Future isDisposed always false

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/queue/ArrayQueue.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/queue/Queue.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/utils/arrayqueue/ArrayQueueTest.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/queue/Utils.kt
There are two edge case issues with ArrayQueue.
**Bug 1**
STR:
1. Offer 7 items to ArrayQueue
2. Poll 7 items
3. Offer 1 item
AR: ArrayQueue.size returns 7
ER: ArrayQueue.size returns 1
**Bug 2**
STR: Offer 8 items to ArrayQueue
AR: ArrayQueue.size returns 0
ER: ArrayQueue.size returns 8
> Fixed bugs in ArrayQueue

- reaktive/build.gradle
> Removed iosTest Gradle task

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/Condition.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
Timeout=0 should wait for 0 nano-seconds, not infinitely
> Fix JVM Condition await with timeout

- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/CombineLatestTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/FlatMapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/UpstreamDownstreamGenericTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/testutils/TestObservable.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/testutils/TestObservableExt.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/testutils/TestObservableObserver.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/testutils/TestObservableObserverExt.kt
Covered `Observable.flatMap()` with tests.
> Tests for flatMap

- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DebounceTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DistinctUntilChangedTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/testutils/TestScheduler.kt
> Tests for debounce

- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ConcatMapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/FlatMapTest.kt
Also improved `flatMap` tests a bit (and removed one useless test)
> Tests for concatMap operator

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/ObserveOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/ObserveOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObserveOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/ObserveOn.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CreateDefaultUncaughtErrorHandler.kt
> Freeze exceptions in observeOn

- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/WithLatestFromTest.kt
> Fixed typo WIthLatestFromTest

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/Various.kt
Use case:
```
observable { emitter ->
emitter.setDisposable(
disposable {
// Cancel something
}
)
}
```
> Make disposable factory public

- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestObserver.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestObserverExt.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestSource.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestSourceExt.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/observable/TestObservable.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/observable/TestObservableExt.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/observable/TestObservableObserver.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/observable/TestObservableObserverExt.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/single/TestSingle.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/single/TestSingleObserver.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/single/TestSingleObserverExt.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/CombineLatestTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ConcatMapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/FlatMapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObservableByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObserveOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/SubscribeOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/UpstreamDownstreamGenericTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ZipTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/FlatMapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/UpstreamDownstreamGenericTests.kt
- Introduced base classes `TestSource` and `TestObserver`
- Refactored `TestObservable` and `TestObservableObserver`
- Introduced `TestSingle` and `TestSingleObserver`
- Added tests for `Single.flatMap`
> Tests for Single.flatMap

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/DisposableWrapper.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/disposable/DisposableWrapperTest.kt
> Tests for DisposableWrapper

- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/maybe/TestMaybe.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/maybe/TestMaybeObserver.kt
- reaktive-test/src/commonMain/kotlin/com/badoo/reaktive/test/maybe/TestMaybeObserverExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Filter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Filter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/NotNull.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ConcatMapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DebounceTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DefaultIfEmptyTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DistinctUntilChangedTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/FlatMapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/MapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObservableToObservableTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObserveOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/SkipTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/SubscribeOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/SwitchIfEmptyTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ThrottleTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/FilterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/FlatMapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/MapTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/NotNullTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/ObserveOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/SingleToMaybeTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/SingleToSingleTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/SubscribeOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/UpstreamDownstreamGenericTests.kt
Both of them transforms `Single` to `Maybe`.
Also we should decide, how to implement `UpstreamDownstreamGenericTests` for cases, when we transform one type of stream to another.
> Single.filter and Single.notNull

- build.gradle
- publication.gradle
> Setup Bintray publication

- reaktive/src/jsMain/kotlin/com/badoo/reaktive/utils/UptimeMillis.kt
> Use hrtime in JS uptimeMillis when running in NodeJS

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/Emitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/CompletableByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/MaybeByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObservableByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/CompletableByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/MaybeByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObservableByEmitterTest.kt
- added isDisposed flag to Emitter interface
- added tests for MaybeByEmitter and CompletableByEmitter
> Added isDisposed flag to Emitter and some tests

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/StartWith.kt
> Added Observable.startWith operator

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ConcatWith.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/StartWith.kt
- sample-android-app/src/main/java/com/badoo/reaktive/sample/android/MainActivity.kt
Basically new methods are just syntax sugar. But they provide more declarative way to describe events flow
> Added Observable.concatWith and Observable.startWith(item) operators

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Vairous.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Vairous.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Vairous.kt
Added `singleOfNever`, `maybeOfNever`, `observableOfNever` and `completableOfNever` builders.
> Add xxxOfNever builders

- reaktive/build.gradle
- reaktive/src/iosCommonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
- reaktive/src/linuxCommonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
@arkivanov Check linux implementation please.
Fixes https://github.com/badoo/Reaktive/issues/154
> Split lock implementation for linux and iOS

- build.gradle
- reaktive-annotations/build.gradle
- reaktive-test/build.gradle
- reaktive/build.gradle
> Don't publish sample-mpp-module

- sample-linuxx64-app/build.gradle
- sample-linuxx64-app/src/linuxMain/kotlin/com/badoo/reaktive/sample/linux/KittenViewImpl.kt
- sample-linuxx64-app/src/linuxMain/kotlin/com/badoo/reaktive/sample/linux/Main.kt
- sample-linuxx64-app/src/linuxMain/kotlin/com/badoo/reaktive/sample/linux/MainScheduler.kt
- sample-linuxx64-app/src/linuxMain/kotlin/com/badoo/reaktive/sample/linux/MainWindow.kt
- sample-linuxx64-app/src/linuxMain/kotlin/com/badoo/reaktive/sample/linux/Utils.kt
- sample-linuxx64-app/src/nativeInterop/cinterop/gtk3.def
- Added GTK3
- Implemented main scheduler for GTK3
- Added simple UI
> Reuse sample-mpp-module in Linux sample app

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Vairous.kt
> Added maybeOfNotNull

- .travis.yml
- buildSrc/src/main/kotlin/PublishPlugin.kt
- reaktive-annotations/build.gradle
- reaktive-testing/build.gradle
- reaktive/build.gradle
Fixes https://github.com/badoo/Reaktive/issues/165
You can review, I am only waiting for CI configuration.
> Configure Bintray publishing from TravisCI

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/Connectable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ConnectableObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Publish.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/SubjectExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicReferenceExt.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/PublishTest.kt
> Added Observable.publish operator

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ConnectableObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Publish.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/RefCount.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/PublishTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RefCountTest.kt
> Added refCount operator

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/DefaultSubject.kt
Access to the `SharedList` must be synchronized
> Fixed race condition in DefaultSubject on unsubscribe

- .travis.yml
Fixes https://github.com/badoo/Reaktive/issues/224
Build = compile everything + check
> Use build task instead of check

- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
Looks like it is last version before Gradle 6.0
> Upgrade Gradle to 5.6.3

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Merge.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Merge.kt
This approach demonstrates better performance
> Optimized Maybe and Single merge operators

- .github/workflows/build.yml
- .travis.yml
- buildSrc/src/main/kotlin/IosPlugin.kt
Generic checks on Actions, release on Travis-CI.
Just approve, don't merge. Want to double check something else.
> Build with GitHub Actions

- .github/workflows/build.yml
- .github/workflows/release.yml
- .travis.yml
Changes:
- Formatted YAML files
- Introduced release on GiHub Actions
- Reverted check on Travis, let's keep it just in case (already noticed problem with force pushes)
- Commented out release on Travis
Also, we need to setup BINTRAY_USER and BINTRAY_KEY again, but for GitHub.
> Release with GitHub Actions

- build.gradle
- buildSrc/src/main/kotlin/IosPlugin.kt
- sample-ios-app/Podfile.lock
- sample-ios-app/README.md
- sample-ios-app/sample-ios-app.xcodeproj/project.pbxproj
Fixes https://github.com/badoo/Reaktive/issues/119
> Build fat framework for iOS

- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/ObservableAsFlowTest.kt
- coroutines-interop/src/jvmJsCommonTest/kotlin/com/badoo/reaktive/coroutinesinterop/FlowAsObservableJvmJsTest.kt
- coroutines-interop/src/nativeCommonTest/kotlin/com/badoo/reaktive/coroutinesinterop/FlowAsObservableNativeTest.kt
Fixes https://github.com/badoo/Reaktive/issues/275
See build log: https://github.com/badoo/Reaktive/commit/0abf34238fe0f72954db6c018ef28d83dd087a04/checks?check_suite_id=302082764#step:4:712
> Add ExperimentalCoroutinesApi annotation for tests

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Replay.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/queue/ArrayQueue.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/queue/Queue.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/PublishGenericTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/PublishTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ReplayTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/utils/queue/ArrayQueueTest.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/utils/queue/PriorityQueue.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/queue/PriorityQueue.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/queue/CopyOnWriteQueue.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/queue/SharedQueue.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Implemented replay with bufferSize

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/AutoConnect.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ConnectableObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/RefCount.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/AutoConnectTest.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Added autoConnect operator

- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CopyOnWriteList.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/SharedList.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/utils/CopyOnWriteListIteratorTest.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/utils/CopyOnWriteListTest.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/utils/queue/CopyOnWriteQueueTest.kt
Used same approach as with `SharedQueue`.
> Optimized SharedList for Native

- reaktive/src/iosCommonMain/kotlin/com/badoo/reaktive/scheduler/MainScheduler.kt
> Freeze tasks in iOS MainScheduler if needed

- build.gradle
> Specify targetSdkVersion

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/TakeWhilePredicate.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/TakeWhilePredicateTest.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
Fixes #332. 
Warning: the k/n compiler was exploding somewhere in this operator in [my project](https://github.com/saket/press/pull/22). I've no idea why.
> Add Observable#takeWhile() operator

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/ZipWith.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ZipWith.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/ZipWith.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
Project reactor has a very convenient zipWith operator. Thought reaktive could benefit from it too.
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#zipWith-reactor.core.publisher.Mono-
> Implement convenient extension to the zip operator.

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Timeout.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/TimeoutTest.kt
> Start timeout on subscribe

- build.gradle
- buildSrc/buildSrc/src/main/kotlin/Deps.kt
- gradle.properties
- sample-android-app/build.gradle
- sample-android-app/src/main/java/com/badoo/reaktive/sample/android/MainActivity.kt
- sample-android-app/src/main/res/layout/activity_main.xml
> Upgrade to Android SDK 29

- README.md
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Replay.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/replay/ReplaySubject.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/replay/ReplaySubjectBuilder.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/queue/ArrayQueue.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/subject/ReplaySubjectTest.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CopyOnWriteList.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/utils/queue/SharedQueueTest.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Add ReplaySubject

- README.md
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/DefaultSubject.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/SubjectExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/replay/ReplaySubjectBuilder.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/unicast/UnicastSubject.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/unicast/UnicastSubjectBuilder.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/subject/SubjectGenericTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/subject/UnicastSubjectTest.kt
- sample-android-app/build.gradle
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Add UnicastSubject

- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/scheduler/TestSchedulerExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/DelaySubscription.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/DelaySubscription.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/DelaySubscription.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/DelaySubscription.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/DelaySubscriptionTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/ObserveOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/SubscribeOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/TimerTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/DelaySubscriptionTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/ObserveOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/SubscribeOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/TimerTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DelaySubscriptionTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/IntervalTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObserveOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/SubscribeOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/TimerTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/DelaySubscriptionTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/ObserveOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/SubscribeOnTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/TimerTest.kt
- tools/binary-compatibility/reference-public-api/reaktive-testing.txt
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Add delaySubscription operators

- buildSrc/src/main/kotlin/PublishPlugin.kt
- buildSrc/src/main/kotlin/Target.kt
Fixes https://github.com/badoo/Reaktive/issues/381
> Handle META target in more precise way when publishing

- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/store/KittenStoreImpl.kt
> Mark class that uses DisposableScope with UseExperimental

- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/binder/KittenBinder.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/store/KittenStoreImpl.kt
> Mark classes that use DisposableScope with UseExperimental

- reaktive/src/jsMain/kotlin/com/badoo/reaktive/utils/queue/PriorityQueue.kt
- reaktive/src/jvmJsCommonTest/kotlin/com/badoo/reaktive/utils/queue/PriorityQueueTest.kt
> Optimise JS PriorityQueue

- buildSrc/src/main/kotlin/DarwinPlugin.kt
Fixes https://github.com/badoo/Reaktive/issues/357
> Do not build fat framework for macOS

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/CompletableByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/DisposableWrapper.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/MaybeByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObservableByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/CompletableByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/disposable/DisposableWrapperTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/MaybeByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObservableByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/SingleByEmitterTest.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/completable/CompletableByEmitter.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/maybe/MaybeByEmitter.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/observable/ObservableByEmitter.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/disposable/DisposableWrapper.kt
- reaktive/src/jvmNativeCommonMain/kotlin/com/badoo/reaktive/completable/CompletableByEmitter.kt
- reaktive/src/jvmNativeCommonMain/kotlin/com/badoo/reaktive/maybe/MaybeByEmitter.kt
- reaktive/src/jvmNativeCommonMain/kotlin/com/badoo/reaktive/observable/ObservableByEmitter.kt
- reaktive/src/jvmNativeCommonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/disposable/DisposableWrapper.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/binder/KittenBinder.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/store/KittenStoreImpl.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Dispose emitters' disposables after terminal events

- README.md
> Add Slack channel link to README

- .github/workflows/build.yml
Does not look like it will help a lot.
Native compilation does not support caching.
Fixes https://github.com/badoo/Reaktive/issues/351
> Caching on CI

- README.md
> Updated schedulers information in the readme

- reaktive-annotations/src/commonMain/kotlin/com/badoo/reaktive/annotations/Annotations.kt
> Add additional targets for EventsOnXxxScheduler-annotations

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/BufferCountSkip.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/BufferCountSkipTest.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Add buffer(count, skip) operator

- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Completable.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Disposable.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Maybe.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Observable.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Scheduler.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Single.kt
- tools/binary-compatibility/reference-public-api/rxjava3-interop.txt
> Rename rxjava3 interop

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/SwitchIfEmpty.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/SwitchIfEmptySingleTest.kt
> Optimize Maybe.switchIfEmpty(Single)

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/OnErrorComplete.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/OnErrorComplete.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/OnErrorComplete.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/OnErrorCompleteTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/OnErrorCompleteTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObservableToObservableForwardTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/OnErrorCompleteTest.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Add on error complete operators

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/AutoConnect.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/AutoConnectTest.kt
> Fix autoConnect does not accept subscriberCount=0

- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Maybe.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Observable.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Single.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Completable.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Maybe.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Observable.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Single.kt
> Fix nullable generic types for rx interop

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/CompletableWrapper.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/MaybeWrapper.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObservableWrapper.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SingleWrapper.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
> Non-null wrappers and additional overloads

- .github/workflows/build.yml
- .github/workflows/release.yml
> Update GitHub Actions to use actions/checkout@v2

- .github/workflows/build.yml
Stolen from https://github.com/badoo/RIBs/blob/master/.github/workflows/ci.yml
> Do not build pull requests twice

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Amb.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Amb.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Amb.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Amb.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/AmbTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/AmbTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/AmbTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/AmbTest.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
Closes: #405 
Doc: http://reactivex.io/documentation/operators/amb.html
> Add amb operators

- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestObserverExt.kt
> Print stack trace in assertNotError

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/BlockingAwait.kt
> Added Completable.blockingAwait function

- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/buildSrc/src/main/kotlin/Deps.kt
- buildSrc/settings.gradle
- coroutines-interop/build.gradle
- settings.gradle.kts
@arkivanov 
It is possible to work with now.
We can force merge this ticket and you can fix all appeared issues (at least 1 small fix and one IR backend error in coroutines lib) in different one.
> 1.4-M3 support

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Completable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/Disposable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/scope/DisposableScope.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Maybe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Observable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/scheduler/Scheduler.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Single.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/behavior/BehaviorSubject.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/publish/PublishSubject.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/replay/ReplaySubject.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/unicast/UnicastSubject.kt
> Add docs for interfaces with factory functions

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/EmitterExt.kt
- sample-mpp-module/src/darwinCommonMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenLoaderImpl.kt
> Add Emitter.setCancellable extension function

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Amb.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Concat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Merge.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Amb.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Merge.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Amb.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/CombineLatest.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Concat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/WithLatestFrom.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Zip.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Amb.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/AmbTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/ConcatTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/MergeTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/AmbTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/MergeTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/AmbTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/CombineLatestTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/WithLatestFromTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ZipTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/AmbTest.kt
> Fix empty collection should complete stream

- reaktive-testing/api/reaktive-testing.api
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestSource.kt
> Added subscriptionCount property to TestSource

- build.gradle
> Bump version to 1.1.17-1.4.0-rc

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/WindowByBoundary.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/WindowByBoundaryTest.kt
Abandoned window is a window that was not subscribed during emission. Such windows should be completed, otherwise upstream may never be disposed in some race conditions. More info here: https://github.com/ReactiveX/RxJava/issues/7056#issuecomment-683101688
As part of #411
> Complete abandoned windows in window(boundaries)

- includedBuild/dependencies/src/main/kotlin/com/badoo/reaktive/dependencies/Deps.kt
> Update Kotlin to 1.4.10

- detekt.yml
- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/WindowByBoundary.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/WindowBySignal.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/WindowByBoundaryTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/WindowBySignalTest.kt
> Added window(opening, closing) operator

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ThrottleLatest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ThrottleLatestTest.kt
> Added throttleLatest operator

- reaktive-testing/api/reaktive-testing.api
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/completable/TestCompletableObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/maybe/TestMaybeObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/observable/TestObservableObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/scheduler/TestSchedulerExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/single/TestSingleObserverExt.kt
> Add test assertions chaining

- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/utils/serializer/SerializerImpl.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/serializer/SerializerImpl.kt
Applied RxJava serialization from RxJava [SerializedEmitter](https://github.com/ReactiveX/RxJava/blob/b3ad0752de398f4536bb88a7b1c77b0b9fbecb87/src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCreate.java#L140) to our `Serializer`. It is faster.
> Derive RxJava serialization

- README.md
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/CompletableWrapper.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/MaybeWrapper.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObservableWrapper.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SingleWrapper.kt
- sample-mpp-module/build.gradle
Closes https://github.com/badoo/Reaktive/issues/530
> remove compiler args.

- sample-ios-app/Podfile.lock
- sample-ios-app/build.gradle.kts
- sample-ios-app/sample-ios-app.xcodeproj/project.pbxproj
- sample-ios-app/sample-ios-app.xcodeproj/xcshareddata/xcschemes/sample-ios-app.xcscheme
- sample-ios-app/sample-ios-app/Base.lproj/Main.storyboard
- sample-ios-app/sample-ios-app/ViewController.swift
Closes https://github.com/badoo/Reaktive/issues/557
> iOS build fix

- rxjava2-interop/build.gradle
- rxjava3-interop/build.gradle
Relates to https://github.com/badoo/Reaktive/issues/550
> Publish kotlinSourcesJar

- .github/workflows/build.yml
> Run linuxArm32Hfp tests per file

- README.md
> Update Readme with JCenter repository

- README.md
- docs/SwiftInterop.md
> Add Reaktive Swift interop docs

- includedBuild/dependencies/src/main/kotlin/com/badoo/reaktive/dependencies/Deps.kt
> Update Kotlin to 1.4.30

- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/completable/CompletableByEmitter.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/maybe/MaybeByEmitter.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/observable/ObservableByEmitter.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
Due to [KT-44764](https://youtrack.jetbrains.com/issue/KT-44764).
Fixes #581.
> Don't inline native source builders

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Amb.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/AsCompletable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/AsMaybe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/AsObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Concat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Defer.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Delay.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/DelaySubscription.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/DoOnAfter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Filter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/FlatMap.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/FlatMapCompletable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/FlatMapIterable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/FlatMapMaybe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/FlatMapObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Flatten.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Map.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/MapIterable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/MapNotNull.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Merge.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/NotNull.kt
> KDocs for Single (part 1/n)

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/ObserveOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/OfType.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/OnErrorResumeNext.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/OnErrorReturn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Repeat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/RepeatUntil.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Retry.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Subscribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SubscribeOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/ThreadLocal.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Timeout.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Timer.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Zip.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/ZipWith.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
> KDocs for Single (part 2)

- .github/workflows/build.yml
- .github/workflows/release-nmtc.yml
- .github/workflows/release.yml
- includedBuild/gradleConfiguration/build.gradle.kts
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/publish/PublishConfigurationPlugin.kt
- tools/check-publication/build.gradle
MavenCentral support https://github.com/badoo/Reaktive/issues/580
> MavenCentral

- .github/workflows/release-nmtc.yml
- .github/workflows/release.yml
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/publish/PublishConfigurationPlugin.kt
https://github.com/badoo/Reaktive/issues/600
> Fix release

- build.gradle
- includedBuild/dependencies/src/main/kotlin/com/badoo/reaktive/dependencies/Deps.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/DarwinPlugin.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/MppConfigurationPlugin.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/publish/PublishConfigurationPlugin.kt
- sample-mpp-module/build.gradle
> Added watchosX64 target

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/operator/Retry.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/RetryTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/RetryTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RetryTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/RetryTest.kt
> Fix retry operator's attempt argument should start from 1

- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/CompletableFromCoroutineTest.kt
- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/MaybeFromCoroutineTest.kt
- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/SingleFromCoroutineTest.kt
- coroutines-interop/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/coroutinesinterop/LaunchCoroutine.kt
- coroutines-interop/src/jvmJsCommonTest/kotlin/com/badoo/reaktive/coroutinesinterop/FlowAsObservableJvmJsTest.kt
- coroutines-interop/src/nativeCommonTest/kotlin/com/badoo/reaktive/coroutinesinterop/FlowAsObservableNativeTest.kt
As part of #626. Will also update the `mt-coroutines` branch in a separate PR.
> Use CoroutineExceptionHandler in coroutines-interop

- coroutines-interop/src/commonMain/kotlin/com/badoo/reaktive/coroutinesinterop/LaunchCoroutine.kt
- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/CompletableFromCoroutineTest.kt
- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/FlowAsObservableTest.kt
- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/MaybeFromCoroutineTest.kt
- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/SingleFromCoroutineTest.kt
Same as #628 but for `mt-coroutines` branch.
The last part for #626.
> Use CoroutineExceptionHandler in coroutines-interop nmtc

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/ObserveOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/OnErrorComplete.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/ThreadLocal.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Merge.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/NotNull.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/ObserveOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/OfType.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/OnErrorComplete.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/OnErrorResumeNext.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/OnErrorReturn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Repeat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/RepeatUntil.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Retry.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Subscribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/SubscribeOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/SwitchIfEmpty.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/ThreadLocal.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Timeout.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Timer.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Zip.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/NotNull.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/ObserveOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/OfType.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/OnErrorReturn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/ThreadLocal.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Timeout.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Zip.kt
> Added KDocs for Maybe, part 2

- .github/workflows/build.yml
- .github/workflows/release-nmtc.yml
- .github/workflows/release.yml
- includedBuild/dependencies/src/main/kotlin/com/badoo/reaktive/dependencies/Deps.kt
- sample-ios-app/build.gradle.kts
- sample-js-browser-app/src/main/kotlin/com/badoo/KittenViewImpl.kt
- sample-js-browser-app/src/main/kotlin/com/badoo/main.kt
- sample-macos-app/build.gradle.kts
- sample-mpp-module/src/jsMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenLoaderImpl.kt
- utils/src/jsMain/kotlin/com/badoo/reaktive/utils/clock/DefaultClock.kt
> Updated Kotlin to 1.6.0, AGP to 7.0.3, migrated deprecated APIs

- README.md
> Describe the new K/N memory model in the readme

- README.md
> Updated Ktor information in Readme

- .github/workflows/release.yml
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/compatibility/BinaryCompatibilityConfigurationPlugin.kt
- settings.gradle.kts
https://youtrack.jetbrains.com/issue/KT-48407/KJS-Yarn-fails-when-both-local-and-remote-library-versions-in-project
> Yarn namespace fix

- README.md
> Updated dependencies configuration in the readme

- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Using.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Using.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Using.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Using.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/UsingTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/UsingTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/UsingTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/UsingTest.kt
> Added `using` operators

- .github/workflows/build.yml
- .github/workflows/release-nmtc.yml
- .github/workflows/release.yml
> Update action versions

- reaktive-testing/build.gradle
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/assert/Assert.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/assert/AssertionError.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/completable/TestCompletableObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/maybe/TestMaybeObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/observable/TestObservableObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/scheduler/TestSchedulerExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/single/TestSingleObserverExt.kt
- reaktive-testing/src/commonTest/kotlin/com/badoo/reaktive/test/assert/AssertTest.kt
> Removed test dependencies from reaktive-testing module

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Repeat.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RepeatTest.kt
> [2.0.0] Repeat with zero returns empty source

- benchmarks/jmh/src/jmh/kotlin/com/badoo/reaktive/benchmarks/jmh/scrabble/ScrabbleReaktive.kt
- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/FlatMap.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/FlatMap.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/FlatMap.kt
> [2.0.0] Reordered arguments of flatMap with resultSelector

- README.md
Just caught a few minor typos in Readme
> fixed a few typos in Readme

- gradle/wrapper/gradle-wrapper.properties
- includedBuild/dependencies/src/main/kotlin/com/badoo/reaktive/dependencies/Deps.kt
- kotlin-js-store/yarn.lock
Kotlin 1.8.0
AGP 7.3.1
Gradle 7.5
Closes #690
> Updated Kotlin to 1.8.0

- benchmarks/jmh/src/jmh/kotlin/com/badoo/reaktive/benchmarks/jmh/scrabble/ScrabbleReaktive.kt
- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Collect.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ToList.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ToMap.kt
> [2.0] Use mutable collections in Observable#collect

- rxjava2-interop/api/rxjava2-interop.api
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Completable.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Maybe.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Observable.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Single.kt
- rxjava3-interop/api/rxjava3-interop.api
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Completable.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Maybe.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Observable.kt
- rxjava3-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Single.kt
> Removed asRxJavaXyzSource extensions

- README.md
> [2.0] Update README.md

- .github/workflows/build.yml
- .github/workflows/release.yml
- coroutines-interop/api/android/coroutines-interop.api
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/MppConfigurationPlugin.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/publish/PublishConfigurationPlugin.kt
- kotlin-js-store/yarn.lock
- reaktive-annotations/api/android/reaktive-annotations.api
- reaktive-testing/api/android/reaktive-testing.api
- reaktive/api/android/reaktive.api
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/disposable/CompositeDisposable.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/disposable/SerialDisposable.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/scheduler/CreateTrampolineScheduler.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/PrintError.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/looperthread/LooperThreadTest.kt
- rxjava2-interop/build.gradle
- rxjava3-interop/build.gradle
- sample-android-app/build.gradle
- utils-internal/api/android/utils-internal.api
- utils-internal/src/linuxCommonMain/kotlin/com/badoo/reaktive/utils/lock/ConditionLock.kt
Also migrated some code and Gradle configs, and fixes various build failures.
It appears that #750 works fine, I was able to publish artifacts locally. Those warnings seem gone.
Please mind that Gradle versions above 8.0.1 are affected by the following issue: https://github.com/gradle/gradle/issues/26154
Fixes: #697 
Fixes: #750
Fixes: #756
> Updated Kotlin to 1.9.10, Gradle to 8.0.1, AGP to 8.0.1, coroutines to 1.7.3

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/ValueCallback.kt
> Make ValueCallback a fun interface
