- jitpack.yml
- reaktive/build.gradle
- target.gradle
Now jitpack will build only reaktive and RxJava2 interoperability lib without launching tests, it's CI's job.
iOS support now can be enabled only explicitly to avoid iOS metadata publication.
> Configuration for jitpack and iOS target is enabled explicitly only

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/AsMaybe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/AsObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/AsSingle.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Concat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/SubscribeSafe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Susbcribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/AsCompletable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/AsObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/AsSingle.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/FlatMap.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/FlatMapObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Flatten.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/SubscribeOn.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/SubscribeSafe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Susbcribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Transform.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/AsCompletable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Collect.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Concat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/SubscribeSafe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Susbcribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Throttle.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ToCompletable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Transform.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/FlatMapMaybe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SubscribeSafe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Susbcribe.kt
A while ago (commit hash 2943757) I was confused by implementation of RxJava2. When you subscribe to an upstream (by calling its `subscribe` method) it may throw an exception. In this case it's actually possible (looks like) to deliver exception via regular `onError` callback instead of `uncaughtErrorHandler`, because we are able to provide a `Disposable` to a downstream before subscribing to an upstream. In this PR I'm fixing the issue.
> Deliver errors to downstreams

- .gitignore
When developing I found that `.DS_Store` and `out/` were able to commit. Now I merged the gitignore of RxJava, but an alternative could be to use [gitignore.io](https://gitignore.io/).
> Merge our gitignore with the RxJava his gitignore

- reaktive/build.gradle
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/BlockingGet.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/Condition.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/utils/Lock.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/MessageQueue.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
We can use CValue instead of manual alloc with Arena. In this case we don't have to manually dispose the allocated memory. This approach is used by `ktor`. Checked with `valgrind`, all good.
> Use CValue instead of Arena

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/DefaultIfEmpty.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/SwitchIfEmpty.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DefaultIfEmptyTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/SwitchIfEmptyTest.kt
This PR adds the operator `defaultIfEmpty`, which is also available on other [implementations of Rx](http://reactivex.io/documentation/operators/defaultifempty.html)
I will probably create another PR adding the `switchIfEmpty`, is that ok?
Both have the same behavior, but `switchIfEmpty` receives another Observable as parameter instead of a value.
> Add defaultIfEmpty and switchIfEmpty operator on Observable

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/atomicreference/AtomicReference.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/atomicreference/AtomicReferenceExt.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/utils/atomicreference/AtomicReference.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/atomicreference/AtomicReference.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomicreference/AtomicReference.kt
Tried to use Reaktive in a multiplatform project and immediately noticed that AtomicReference is needed. Could not find any good existing library, [AtomicFU](https://github.com/Kotlin/kotlinx.atomicfu) is not thread safe in Native.
> Make AtomicReference public

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/BlockingGet.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/Condition.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/ConditionExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/LockExt.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/utils/Lock.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/MessageQueue.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/Lock.kt
Well, after further investigations it appears to be impossible to avoid manual memory freeing when using `cinterop` from Kotlin. The [implementation](https://github.com/ktorio/ktor/blob/master/ktor-utils/posix/src/io/ktor/util/LockNative.kt) from `ktor` does not work either. I have raised an [issue](https://github.com/ktorio/ktor/issues/1135) for them. Reverted the commit fafa90e1ec82b896148eb30748235d54d89123ec and updated the code a bit.
Fixes https://github.com/badoo/Reaktive/issues/62
> Fixed broken Native Lock and Condition

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/CompleteCallback.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/Consumer.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/SuccessCallback.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/ValueCallback.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/CompletableCallbacks.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/MaybeCallbacks.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Transform.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/FlatMap.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObservableCallbacks.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/AsMaybe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SingleCallbacks.kt
Extracted `onNext`, `onSuccess` and `onComplete` callbacks to a separate interfaces. Added `Consumer` typealias. Now we can depend only on what we really need, e,g, we can pass an `Observable` or a `Subject` to a function accepting just `Consumer` without any extra allocations. Will be useful if we will be migrating `MviCore` to `Reaktive`.
> Better callbacks interface segregation

- .gitignore
- .travis.yml
- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/JsPlugin.kt
- buildSrc/src/main/kotlin/Versions.kt
- reaktive/build.gradle
- sample-js-browser-app/build.gradle
`jsTest` task does not run tests.
To run test we need to install `mocha` (probably any JS test engine is fine) and launch it manually through `node mocha reaktive-test.js` call. 
Fixes https://github.com/badoo/Reaktive/issues/53
> Introduce JsPlugin for configuration and run tests on NodeJS

- .travis.yml
- build.gradle
- buildSrc/src/main/kotlin/IosPlugin.kt
- buildSrc/src/main/kotlin/JsPlugin.kt
- Move iOS configuration to plugin
- Remove TODO to turn on/off `check` task dependency on `iosTask`
- Make `check` depends on `iosTask` and all iOS binaries compilation tasks to verify, that lib can be built for all platforms and to simplify Travis configuration (fixes https://github.com/badoo/Reaktive/issues/81)
- Use new API to get path to executable iOS test binary (fixes https://github.com/badoo/Reaktive/issues/89)
> iOS plugin

- sample-ios-app/build.gradle
- sample-ios-app/xcode/sample-ios-app/ViewController.swift
- Configure `export` for iOS sample
- Replace generated Obj-C names with new generated Swift names (support was added recently)
- Fixes https://github.com/badoo/Reaktive/issues/111
https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries
> Export dependencies and change sample to support new swift declarations

- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/JsPlugin.kt
- buildSrc/src/main/kotlin/Versions.kt
- gradle.properties
- gradle/versions.gradle.kts
- rxjava2-interop/build.gradle
- sample-js-browser-app/build.gradle
- settings.gradle
Moved some dependency versions to separate `versions.gradle.kts` file and set them as project extra.
In future should probably be implemented as `resolutionStrategy` for all projects.
> Kotlin version management

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/DefaultSubject.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicList.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/subject/SubjectGenericTests.kt
Adding elements to immutable List is ~20% faster in K/N than with immutable Set. As we don't need constant time `contains` we can replace `Set` with `List`.
> Use List instead of Set in DefaultSubject

- .travis.yml
> Android builds are only supported on our Trusty image at this time hence you’ll need to explicitely specify dist: trusty in your .travis.yml file.  [Read more](https://docs.travis-ci.com/user/languages/android/)
> Use trusty dist

- sample-mpp-module/build.gradle
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/Config.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/SingleLifeEvent.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/binder/KittenBinder.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/binder/KittenStateToViewModelMapper.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/binder/KittenViewEventToIntentMapper.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/store/KittenLoader.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/store/KittenStore.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/store/KittenStoreBuilder.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/store/KittenStoreImpl.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/view/AbstractKittenView.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/view/KittenView.kt
- sample-mpp-module/src/jsMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenLoaderImpl.kt
- sample-mpp-module/src/jsMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenStoreBuilderImpl.kt
- sample-mpp-module/src/jvmMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenLoaderImpl.kt
- sample-mpp-module/src/jvmMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenStoreBuilderImpl.kt
- sample-mpp-module/src/linuxX64Main/kotlin/com/badoo/reaktive/samplemppmodule/Curl.kt
- sample-mpp-module/src/linuxX64Main/kotlin/com/badoo/reaktive/samplemppmodule/KittenLoaderImpl.kt
- sample-mpp-module/src/linuxX64Main/kotlin/com/badoo/reaktive/samplemppmodule/KittenStoreBuilderImpl.kt
- sample-mpp-module/src/main/AndroidManifest.xml
- sample-mpp-module/src/nativeInterop/cinterop/libcurl.def
- settings.gradle
This is the first part. The next parts will be updating Android, JS and Linux sample apps. The new sample-mpp-module is implemented in "MVI" style. Apps should only implement views. I have code complete for Android, JS and Linux (GTK3).
> Addde sample-mpp-module with JVM, LinuxX64 and JS targets

- reaktive/build.gradle
- reaktive/src/androidMain/kotlin/com/badoo/reaktive/utils/PrintError.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/SubscribeInternal.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Subscribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/DisposableExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Subscribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Subscribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Subscribe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/PrintError.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/UncaughtErrorHandler.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/Utils.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/SubscribeTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/SubscribeTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/SubscribeTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/test/Utils.kt
- reaktive/src/iosCommonMain/kotlin/com/badoo/reaktive/utils/CurrentThread.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/utils/PrintError.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/base/exceptions/CompositeException.kt
- reaktive/src/jvmCommonTest/kotlin/com/badoo/reaktive/test/DoInBackground.kt
- reaktive/src/jvmMain/kotlin/com/badoo/reaktive/utils/PrintError.kt
- reaktive/src/jvmNativeCommonTest/kotlin/com/badoo/reaktive/test/DoInBackground.kt
- reaktive/src/jvmNativeCommonTest/kotlin/com/badoo/reaktive/utils/ThreadLocalStorageThreadingTest.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/PrintError.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/completable/SubscribeTestNative.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/maybe/SubscribeTestNative.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/observable/SubscribeTestNative.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/single/SubscribeTestNative.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/test/DoInBackground.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/utils/CurrentThreadTest.kt
Quite a big change, extracted boilerplate to a separate file.
Fixes #176
> Handle exceptions in subscribe callbacks

- rxjava2-interop/build.gradle
It is much easier just to rename publication name (that is used only in Gradle) than to do fixes inside plugin.
> Make publication name match MPP naming model

- jitpack.yml
Not sure if Jitpack still tries to build us or not, but now it will be disabled by overriding build steps.
> Skip Jitpack builds

- reaktive/src/commonTest/kotlin/com/badoo/reaktive/utils/serializer/SerializerTest.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/scheduler/BufferedExecutor.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/utils/queue/QueueExt.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/utils/serializer/SerializerImpl.kt
This PR addresses performance of `Serializer` and `BufferedExecutor` in JVM. As per JMH [benchmarks](https://github.com/ShikaSD/multiK/tree/master/bench/src) some operators are slower than RxJava2 (e.g. `flatMap`). This PR improves performance of `Serializer` and `BufferedExecutor` in JVM, so e.g. `flatMap` is now around ~3x faster.
> User synchronized instead of Lock in SerializerImpl in JVM and JS

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/PrintError.kt
Same as in `Schedulers.kt`, otherwise it's impossible to access this field from non main threads.
> Annotate _isPrintErrorEnabled with @SharedImmutable

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/CompositeDisposable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/DoOnBefore.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/DoOnBefore.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/disposable/CompositeDisposable.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/disposable/CompositeDisposable.kt
Separate implementations of CompositeDisposable for Native and JVM/JS. For the last ones we can use mutable collections with synchronization (JVM). Improves Scrabble benchmark results by -67%.
> Split CompositeDisposable for Native and JVM/JS

- .travis.yml
Our cache is too huge now (3.5 GB). Looks like diff calculation for cache takes 5-10 minutes every build. I want to try to remove `.konan` folder from cache and check, maybe it is faster to download it every time.
https://docs.travis-ci.com/user/caching/#things-not-to-cache
Official documentation is not so obvious.
> Large files that are quick to install but slow to download do not benefit from caching
I can tell the same about Gradle wrapper, just ZIP archive, that should be extracted. But still they add it to cache by default.
I will drop all caches after ticket is merged.
> Remove .konan from cache

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/DisposableEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/CompletableByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/DisposableWrapper.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/MaybeByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObservableByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/disposable/DisposableWrapper.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/disposable/DisposableWrapper.kt
Our Scrabble results are already reduced from ~205 ms to ~131 ms on my machine. This PR improves it further to ~124 ms.
> Omptimized SourceByEmitter builders

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Various.kt
In such a simple cases it's better to avoid emitters allocations
> Optimized source builders

- .gitignore
I don't think we will ever use `build` as package name.
> Add all build folders to .gitignore

- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestObserver.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/completable/TestCompletableObserver.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/completable/TestCompletableObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/maybe/TestMaybeObserver.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/maybe/TestMaybeObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/observable/TestObservableObserver.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/observable/TestObservableObserverExt.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/single/TestSingleObserverExt.kt
* Cleanup assertion messages for testing API
* Move `isError` property inside `TestObserver`, as it's done with `isComplete`, `isSuccess`, etc.
> Add more descriptive assertion messages

- build.gradle
- buildSrc/buildSrc/src/main/kotlin/Deps.kt
Version of coroutines used is `1.3.2-native-mt-1`. Let me know if I missed something: [Kotlin 1.3.60 release notes](https://blog.jetbrains.com/kotlin/2019/11/kotlin-1-3-60-released/).
Fixes #303
> Update Kotlin to 1.3.60

- gradle.properties
Probably 512 MB is not enough.
Can't check, I use OpenJ9 because it consumes 2x less memory than default JRE.
> Give Gradle more memory and enable caching

- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/base/TestObserver.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/CompletableByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/MaybeByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObservableByEmitter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/SingleByEmitter.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/CompletableByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/MaybeByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ObservableByEmitterTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/SingleByEmitterTest.kt
Found a bug - if you call terminal callbacks of an emitter recursively then the stream terminates twice.
Solution - dispose before call downstream's terminal callbacks.
> Prevent recursive termination in XxxByEmitter

- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Completable.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Disposable.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Maybe.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Observable.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Scheduler.kt
- rxjava2-interop/src/main/kotlin/com/badoo/reaktive/rxjavainterop/Single.kt
- tools/binary-compatibility/reference-public-api/rxjava2-interop.txt
> Rename RxJava2 interop converters to avoid clashing

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/operator/Publish.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ReplayTest.kt
So there was a bug in RxJava's `Observable.replay()` operator, and it was derived by Reaktive. This bug was recently fixed (https://github.com/ReactiveX/RxJava/issues/6920). We need to update our implementation as well.
This also fixes #420.
> Update replay after rxjava bug fix

- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DefaultIfEmptyTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DelaySubscriptionTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnAfterCompleteTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnAfterDisposeTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnAfterErrorTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnAfterFinallyTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnAfterNextTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnAfterSubscribeTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnAfterTerminateTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnBeforeCompleteTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnBeforeDisposeTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnBeforeErrorTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnBeforeFinallyTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnBeforeNextTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnBeforeSubscribeTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/DoOnBeforeTerminateTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/OnErrorResumeNextTest.kt
We can share tests for simple operators that should just forward all values from the upstream.
> Introduce ObservableToObservableForwardTests

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/behavior/BehaviorObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/behavior/BehaviorRelay.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/behavior/BehaviorSubject.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/subject/BehaviorSubjectTest.kt
- tools/binary-compatibility/reference-public-api/reaktive.txt
Fixes #456 
Extracted `BehaviorRelay` and `BehaviorObservable` interfaces. Please check the binary compatibility files change as well, looks like it should not break anything.
> Extract read only interfaces for BehaviorSubject

- gradle.properties
One of the failures of https://github.com/badoo/Reaktive/pull/466 was OutOfMemoryError.
> Increase Gradle memory limit

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/scope/DisposableScope.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/scope/DisposableScopeBuilder.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/scope/DisposableScopeExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/scope/DisposableScopeImpl.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/disposable/scope/DisposableScopeImplTest.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/binder/KittenBinder.kt
- sample-mpp-module/src/commonMain/kotlin/com/badoo/reaktive/samplemppmodule/store/KittenStoreImpl.kt
- Removed `fun <T : CompleteCallback> T.scope(): T`
- Added `fun <T> T.scope(onDispose: (T) -> Unit): T`
- Removed `ExperimentalReaktiveApi` annotations
- Updated tests
- Updated samples
Closes #459
> Stabilize DisposableScope API

- reaktive-testing/api/reaktive-testing.api
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/scheduler/TestScheduler.kt
Advancing time does not account for resubscriptions for example in `retry` or `repeat` when it's conditional
Reason is the scheduler will just advance time and check if any current tasks are scheduled, it will just execute
But in case any of these tasks will cause a resubscription that should run inside the time frame of the advanced time
For example,
If we have a repeatUntil that will delay 10 seconds for 5 times (based on a network call that will return the number of repeats and interval)
If we advance time by 50 seconds, it is expected to have 5 emissions but that's not the case, we will just get 1.
Proposed fix:
Applying what was suggested in https://github.com/badoo/Reaktive/pull/470#issuecomment-636376085
Instead of blindly advancing time, it will advance time and update task list …
> Fix TestScheduler advanceTime

- .github/workflows/build.yml
- gradle.properties
Probably fixes https://github.com/badoo/Reaktive/issues/479
`--no-parallel` affects multi-module projects a lot.
> kotlin.native.disableCompilerDaemon

- utils/api/utils.api
- utils/src/commonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicBooleanExt.kt
- utils/src/commonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicIntExt.kt
- utils/src/commonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicLongExt.kt
- utils/src/commonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicReferenceExt.kt
This allows to use property delegation:
```kotlin
class MyClass {
private val _string = AtomicReference<String?>(null)
var string: String? by _string
}
```
Closes #492
> Add getValue and setValue extensions for Atomics

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/WindowByBoundary.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/WindowByBoundaryTest.kt
As part of #411 
Operators implemented:
- http://reactivex.io/RxJava/javadoc/io/reactivex/Observable.html#window-io.reactivex.ObservableSource-
- http://reactivex.io/RxJava/javadoc/io/reactivex/Observable.html#window-long-java.util.concurrent.TimeUnit-long-boolean-
Some tricky behaviours:
- The `upstream` _should not_ be disposed if the `downstream` is disposed but the last window is still subscribed, but the `boundaries` stream _should_ be disposed. If then the last window is disposed, the `upstream` should be disposed as well.
- If either `upstream` or `boundaries` stream is completed then everything should be cancelled and completed as well
- `UnicastSubject` is used as window, so it can be subscribed only once but all values are accumulating until the window is susbcribed
> Added Observable.window(boundaries) operator

- .github/workflows/release-nmtc.yml
I think we'll need to publish mt coroutines interop multiple times, so would be nice to automate. The idea is to create a tag in the `mt-cotourines` branch every time after a release and have this workflow executed. Not sure about the yaml filter.
> Automate nmtc

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/WindowSized.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/WindowSizedTest.kt
As part of #411
Feels like i don't cover all cases in tests. Too complicated operator.
`WindowSized` is the appropriate name?
I'm embarrassed for the long wait, relocated to another city this month.
> Added Observable.window(count, skip) operator

- .github/workflows/release.yml
The job fails without "apt get update", but I think we don't need these packages at all.
> Remove "apt get install" from check publication

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/ValueCallbackExt.kt
Just for convenience.
Closes #549
> Add operator fun invoke for ValueCallback

- .github/workflows/build.yml
- reaktive/src/jvmNativeCommonTest/kotlin/com/badoo/reaktive/scheduler/AllBackgroundSchedulersTest.kt
Used the hint provided by @CherryPerry about `uraimo/run-on-arch-action` action.
Looks like this emulator is quite slow, so `AllBackgroundSchedulersTest` was hitting timeout. Updated the test. Other tests look fine.
Closes #504
> Run linuxArm32Hfp tests on CI

- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CreateDefaultUncaughtErrorHandler.kt
> Use abort() instead of exitProcess() in native reaktiveUncaughtErrorHandler

- includedBuild/dependencies/src/main/kotlin/com/badoo/reaktive/dependencies/Deps.kt
> Update Kotlin to 1.4.20, also bump Coroutines, RxJava3 and AGP

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/BufferCountSkip.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/BufferCountSkipTest.kt
> Fix Observable.buffer skip logic

- sample-linuxx64-app/build.gradle
- sample-linuxx64-app/src/linuxMain/kotlin/com/badoo/reaktive/sample/linux/MainScheduler.kt
- sample-linuxx64-app/src/nativeInterop/cinterop/gtk3.def
CI `ubuntu-latest` now uses Ubuntu 20.04.2 and the linuxX64 sample app compilation fails. We need to also include `harfbuff` lib.
Also fixed `IncorrectDerefeceException` crash in the sample app's custom `MainScheduler`.
> Include harfbuzz lib to linuxX64 sample app

- gradle.properties
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/JsPlugin.kt
- reaktive-testing/src/commonMain/kotlin/com/badoo/reaktive/test/single/TestAwait.kt
- reaktive-testing/src/commonTest/kotlin/com/badoo/reaktive/test/single/TestAwaitTest.kt
> Enable JS IR backend

- reaktive/api/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/FlatMap.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/FlatMapCompletable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/FlatMapMaybe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/FlatMapSingle.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/RefCounterExt.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/FlatMapTest.kt
Closes #612 
Related docs: http://reactivex.io/RxJava/javadoc/io/reactivex/Observable.html#flatMap-io.reactivex.functions.Function-boolean-int-
> Added maxConcurrency argument to flatMap

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/DisposableWrapper.kt
It should be WARNING in this release, and ERROR in the next minor release.
> Reduce DisposableWrapper deprecation level to WARNING

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/CombineLatest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/CombineLatestTest.kt
> Supply copies of the List to mapper in combineLatest

- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/publish/PublishConfigurationPlugin.kt
I added the new Apple silicon targets in #636, but forgot to add publications. This PR adds missing publications for Apple silicon targets.
> Add Apple silicon target publications

- gradle.properties
Currently the build often fails with random errors, including `java.lang.OutOfMemoryError: Metaspace` errors. It seems that removing the `XX:MaxMetaspaceSize=512m` setting fixes the issue.
> Removed MaxMetaspaceSize setting

- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/AsMaybe.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/AsObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/BlockingAwait.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Concat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Repeat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/RepeatUntil.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/DoOnAfter.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/FlatMapCompletable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/FlatMapCompletable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Interval.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Replay.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/SwitchMapCompletable.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/AsMaybeTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/AsObservableTests.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/DoOnAfterCompleteTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/IntervalTest.kt
Part of the #620 
* Remove generics from `Completable.asMaybe` and `Completeable.asObservable`
* Rename parameter `action` to `consumer` (See notes)
* Swap parameters for the observable interval and make default for delay as period value
* Add default parameter values and remove overridden versions
* There are more `action` named parameters
* IDE shows me unused function warning - should we suppress it?
> [2.0.0] Small api changes

- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/operator/Retry.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Repeat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Retry.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Repeat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Retry.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Repeat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Retry.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Repeat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Retry.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/RetryTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/RetryTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RepeatTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RetryTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/RetryTest.kt
Change type and rename parameters for Retry and Repeat #620.
* Rename `count` to `times` for `Repeat` and make it Long. Also change default parameter value to `Long.MAX_VALUE`.
* Change type to long for `Retry` (see notes)
* Small changes around tests
* Unfortunately if I put default value for retry we have clashing function calls. If my knowledge of Kotlin is correct, then I have to provide some parameter to help compiler to resolve type. This might be inconvenient for the user of the library. However, version with default selector is less performant. We could remove there default parameter value and use the simpler instead.
> [2.0.0] Retry and repeat changes

- build.gradle
- gradle.properties
- includedBuild/dependencies/build.gradle.kts
- includedBuild/dependencies/src/main/kotlin/com/badoo/reaktive/dependencies/Deps.kt
- includedBuild/gradleConfiguration/build.gradle.kts
- kotlin-js-store/yarn.lock
- reaktive/src/darwinCommonMain/kotlin/com/badoo/reaktive/scheduler/MainScheduler.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/utils/SynchronizedCompat.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/SynchronizedCompat.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/disposable/CompositeDisposable.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/disposable/SerialDisposable.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/observable/SerializedObservableCallbacks.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/scheduler/BufferedExecutor.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/utils/SynchronizedCompat.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/utils/serializer/SerializerImpl.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/scheduler/BufferedExecutor.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/serializer/SerializerImpl.kt
- settings.gradle.kts
This PR updates Kotlin to 1.6.21 and coroutines to 1.6.1. Since Kotlin 1.6.20, HMPP is enabled by default. So this PR is a follow-up to #638.
[KT-48811](https://youtrack.jetbrains.com/issue/KT-48811) is marked as fixed, however it's still relevant and is now being tracked in [KT-52193](https://youtrack.jetbrains.com/issue/KT-52193). Because of this, I had to supply default values to atomics in shared source sets, even though they have default values specified in `expect` common.
> Updated Kotlin to 1.6.21 with HMPP enabled

- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Throttle.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/ThrottleTest.kt
> Added scheduler argument to throttle operator

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/RepeatWhen.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RepeatWhenTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/RepeatWhenTest.kt
Also renamed the handler's argument from `repeatNumber` to `attempt`, for consistency with the `retry` operator. Should be fine because it's not part of the API and basically just a hint.
> Added counter tests for repeatWhen

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Scan.kt
For consistency with RxJava.
As part of #620.
> [2.0.0] Renamed Observable#scan `accumulate` argument to `accumulator`

- gradle.properties
- includedBuild/dependencies/src/main/kotlin/com/badoo/reaktive/dependencies/Deps.kt
- kotlin-js-store/yarn.lock
- sample-mpp-module/build.gradle
Since Kotlin 1.7.20 the new K/N memory model is enabled by default. Since Reaktive still supports the legacy model, some of our tests fail if freezing is disabled. I enabled the legacy model for now, while Reaktive supports it (perhaps until v2.0). This should not affect clients' experience.
> Updated Kotlin to 1.7.21

- .github/workflows/build.yml
- .github/workflows/release-nmtc.yml
- .github/workflows/release.yml
Looks like it is better to match Xcode version with particular Kotlin version.
```
java.lang.IllegalStateException: command '/usr/bin/xcrun' exited with errors (exit code: 148)
Invalid device: Apple Watch Series 5 - 44mm
```
Issue: https://youtrack.jetbrains.com/issue/KT-54814
> Hardcode Xcode version because Kotlin expects particular emulators

- docs/SwiftInterop.md
The maven artifact `reaktive-ios64` appears to have been renamed to `reaktive-iosarm64` starting at version 1.2.1
> Update documentation for reaktive-iosarm64 rename

- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Throttle.kt
> [2.0.0] Removed deprecated throttle operator without Scheduler argument

- docs/SwiftInterop.md
- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/BehaviorObservableWrapper.kt
This is useful for exposing stateful observables to Swift (e.g. `BahaviorSubject` or `BehaviorObservable`), so reading the current state is also possible.
Also fixes #695.
> Added BehaviorObservableWrapper

- .github/workflows/build.yml
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/DarwinPlugin.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/MppConfigurationExtension.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/MppConfigurationPlugin.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/publish/PublishConfigurationPlugin.kt
- reaktive-annotations/build.gradle
- reaktive-testing/build.gradle
- reaktive/build.gradle
- sample-mpp-module/build.gradle
- utils/build.gradle
Those targets are deprecated since Kotlin 1.8.20 and will be removed in Kotlin 1.9.20 (see the [blog post](https://blog.jetbrains.com/kotlin/2023/02/update-regarding-kotlin-native-targets/)).
As part of #620
> Removed deprecated iosArm32 and linuxArm32Hfp targets

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/queue/PriorityQueue.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/utils/queue/PriorityQueueTest.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/DelayQueue.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/utils/DelayQueueTest.kt
Now we can replace the atomic-based queue with `PriorityQueue` in native `DelayQueue`. Also added `peek` and `iterator` back to `PriorityQueue`, they were removed in #718.
> [2.0] Optimized DelayQueue

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Sample.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/SampleTest.kt
Discovered and fixed two bugs in `Observable#sample`:
- Emits the last value again and again on every period hit.
- Does not emit `null` values.
See the related [RxJava doc](http://reactivex.io/RxJava/javadoc/io/reactivex/Observable.html#sample-long-java.util.concurrent.TimeUnit-io.reactivex.Scheduler-).
> [2.0] Fix sample operator emits same values and does not emit nulls

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/operator/Retry.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/CombineLatest.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ConcatMap.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/FlatMap.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Interval.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Repeat.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/RepeatUntil.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Skip.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/SwitchIfEmpty.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/TakeObservable.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ThrottleLatest.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/WindowByBoundary.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/WindowBySignal.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/RepeatUntil.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/RepeatWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/unicast/UnicastSubjectBuilder.kt
There are cases where atomics are used only due to legacy freezings, the access is already synchronized anyway. Now we can use normal variables there. The access is already synchronized by either `serializer`, or the upstream calling the observer synchronously.
> [2.0] Replaced atomics with simple variables

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/RefCount.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RefCountTest.kt
Modified the refCount function to account for the subscribeCount before the actual subscribe. This resolved an issue when you are using both replay, and firstOrError.
I have attempted to create a Unit test to replicate the issue but I was unsuccessful, I am not familiar enough with the testing environment to recreate it in Unit Tests. I  have left the test in comments however.
To replicate the issue: 
- create an observable
- apply replay(1).refcount() and store separately
- subscribe once to the second observable which causes a connection
- send a value through the upstream
- THEN subscribe again to the second observable using firstOrError()
This results in the connectable being disconnected. The reason being is with replay and a value stored in the buffer, the single subscribes, …
> Undesirable disconnect fix with replay, refCount, and firstOrError

- benchmarks/jmh/build.gradle
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/MppConfigurationPlugin.kt
- rxjava2-interop/build.gradle
- rxjava3-interop/build.gradle
Also specified `jvmToolchain` for benchmarks, it seems to produce more stable results across different build environments.
> [2.0] Specified jvmTarget for all projects

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/AbstractSubject.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/LinkedQueue.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/LinkedQueueExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/behavior/BehaviorSubjectBuilder.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/behavior/BehaviorSubjectImpl.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/publish/PublishSubjectBuilder.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/replay/ReplaySubjectBuilder.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/replay/ReplaySubjectImpl.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/unicast/UnicastSubjectBuilder.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/subject/unicast/UnicastSubjectImpl.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/subject/BehaviorSubjectTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/subject/ReplaySubjectTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/subject/UnicastSubjectTest.kt
The idea is to use a singly-linked queue. On each subscription, acquire the current head and emit the item (or all items till the end, depending on the type of the subject). Then pass the last emitted item via serializer and emit any new items when processed.
Observers must not miss any new items that are sent to the subject cuncurrently after initial items are emitted (synchronously on subscription). E.g. if `BehaviorSubject` holds item A, and a new observer receives that item synchronously on subscription, and new items B, C and D are sent to the subject concurrently, then that observer must receive B, C and D eventually.
Fixes #727
> [2.0] Fixed subjects not emitting initial values synchronously on subscription under load

- coroutines-interop/src/jvmCommonTest/kotlin/com/badoo/reaktive/coroutinesinterop/CoroutineContextSchedulerJvmTest.kt
- coroutines-interop/src/jvmCommonTest/kotlin/com/badoo/reaktive/coroutinesinterop/SchedulerCoroutineDispatcherJvmTest.kt
- coroutines-interop/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/coroutinesinterop/CoroutineContextScheduler.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/scheduler/TrampolineScheduler.kt
- reaktive/src/jsMain/kotlin/com/badoo/reaktive/scheduler/CreateTrampolineScheduler.kt
- utils-internal/src/commonMain/kotlin/com/badoo/reaktive/utils/Constants.kt
- utils-internal/src/commonMain/kotlin/com/badoo/reaktive/utils/clock/Clock.kt
- utils-internal/src/commonTest/kotlin/com/badoo/reaktive/utils/clock/DefaultClockTest.kt
- utils-internal/src/jsMain/kotlin/com/badoo/reaktive/utils/clock/DefaultClock.kt
- utils-internal/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/clock/DefaultClock.kt
- utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/clock/DefaultClock.kt
Started migrating APIs from millis to `kotlin.time.Duration`. This is the 1st PR out of 3.
Converted `Clock` and all its usages. The next PR will address `Scheduler` and all its implementations.
As part of #620.
> [2.0] Use Duration in Clock (1 of 3)

- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/CachedLooperThreadStrategy.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/scheduler/CreateIoScheduler.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/scheduler/SchedulerImpl.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/DelayQueue.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/ExpirationPool.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/looperthread/LooperThreadTest.kt
- reaktive/src/nativeCommonTest/kotlin/com/badoo/reaktive/utils/DelayQueueTest.kt
Last preparatory PR before migrating schedulers.
> [2.0] Use Duration in DelayQueue, ExpirationPool and LooperThread (2 of 4)

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Various.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/plugin/ReaktivePlugin.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/plugin/ReaktivePlugins.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/Various.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/plugin/ReaktivePluginsTest.kt
New methods with default implementations can be added to the `ReaktivePlugin` interface without breaking the API.
As part of #620.
> Stabilized plugins

- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Buffer.kt
Aligned with RxJava.
As part of #620.
> Make buffer limit arguments of type int instead of long

- coroutines-interop/build.gradle
- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/CoroutineContextSchedulerTest.kt
- coroutines-interop/src/commonTest/kotlin/com/badoo/reaktive/coroutinesinterop/SchedulerCoroutineDispatcherTest.kt
- coroutines-interop/src/main/AndroidManifest.xml
- gradle.properties
- gradle/libs.versions.toml
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/MppConfigurationPlugin.kt
- kotlin-js-store/yarn.lock
- reaktive-annotations/build.gradle
- reaktive-annotations/src/main/AndroidManifest.xml
- reaktive-testing/build.gradle
- reaktive-testing/src/main/AndroidManifest.xml
- reaktive/build.gradle
- reaktive/src/main/AndroidManifest.xml
- sample-android-app/build.gradle
- sample-android-app/src/main/AndroidManifest.xml
- sample-mpp-module/build.gradle
- sample-mpp-module/src/main/AndroidManifest.xml
- utils-internal/build.gradle
- utils-internal/src/main/AndroidManifest.xml
Also updated coroutines to 1.7.1 and removed `@OptIn(ExperimentalCoroutinesApi)` annotation from `runTest`.
Closes #749.
> [2.0] Kotlin 1.8.21 and new source set layout

- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/RefCount.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RefCountTest.kt
- reaktive/src/jvmNativeCommonTest/kotlin/com/badoo/reaktive/observable/RefCountThreadingTest.kt
Fixed a race condition in `refCount` when the second connection is performed concurrently while the first connection is still being disconnected.
Also fixed a bug when the upstream is not connected when disposed synchronously.
> Fixed a race condition in refCount

- .gitignore
- gradle.properties
- gradle/libs.versions.toml
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/JsPlugin.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/MppConfigurationPlugin.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/configuration/Utils.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/detekt/DetektConfigurationPlugin.kt
- includedBuild/gradleConfiguration/src/main/kotlin/com/badoo/reaktive/publish/PublishConfigurationPlugin.kt
- kotlin-js-store/yarn.lock
- reaktive-testing/src/jvmNativeCommonMain/kotlin/com/badoo/reaktive/test/single/AsyncTestResult.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/CompositeDisposable.kt
- reaktive/src/jvmJsCommonMain/kotlin/com/badoo/reaktive/disposable/CompositeDisposable.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/disposable/CompositeDisposable.kt
- sample-android-app/build.gradle
- sample-mpp-module/build.gradle
- utils-internal/api/android/utils-internal.api
- utils-internal/api/jvm/utils-internal.api
Also added logic to avoid exporting the sample iOS framework if not building for Xcode. This makes CI builds much faster, as it doesn't link all architectures.
Closes #776.
> Updated Kotlin to 2.0.0, coroutines to 1.8.1, Detekt to 1.23.6, AGP to 8.2.0

- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/RetryWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/maybe/RetryWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/RetryWhen.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/single/RetryWhen.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/completable/RetryWhenTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/maybe/RetryWhenTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/observable/RetryWhenTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/single/RetryWhenTest.kt
> Added retryWhen operator

- reaktive/src/jvmNativeCommonTest/kotlin/com/badoo/reaktive/observable/RefCountThreadingTest.kt
This affected code is supposed to wait for the disconnection to begin (the `Disposable { ... }` above should begin its execution concurrently). However, due to the incorrect condition the test sometimes fails with timeout.
> Fixed incorrect condition in RefCountThreadingTest

- reaktive/api/android/reaktive.api
- reaktive/api/jvm/reaktive.api
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/base/ErrorCallbackExt.kt
- reaktive/src/commonMain/kotlin/com/badoo/reaktive/utils/HandleSourceError.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/test/TestErrorCallback.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/utils/TryCatchAndHandleTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/utils/TryCatchTest.kt
- reaktive/src/commonTest/kotlin/com/badoo/reaktive/utils/TryCatchWithOnSuccessTest.kt
- reaktive/src/jsCommonMain/kotlin/com/badoo/reaktive/utils/HandleSourceError.kt
- reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/utils/HandleSourceError.jvm.kt
- reaktive/src/jvmTest/kotlin/com/badoo/reaktive/utils/HandleReaktiveErrorJvmTest.kt
- reaktive/src/jvmTest/kotlin/com/badoo/reaktive/utils/MyVirtualMachineError.kt
- reaktive/src/jvmTest/kotlin/com/badoo/reaktive/utils/TryCatchAndHandleJvmTest.kt
- reaktive/src/jvmTest/kotlin/com/badoo/reaktive/utils/TryCatchJvmTest.kt
- reaktive/src/jvmTest/kotlin/com/badoo/reaktive/utils/TryCatchWithOnSuccessJvmTest.kt
- reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/HandleSourceError.native.kt
Rethrow fatal exceptions immediately on JVM (`VirtualMachineError`, `ThreadDeath` and `LinkageError`). Couldn't determine any fatal exceptions on other platforms.
Fixes #784.
> Rethrow fatal errors on JVM
